---
title: "Spain Election Analysis"
author: "Igor Morzan"
date: "4/9/2019"
output: html_document
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(dplyr)
library(plotly)

spain_polling <- read_csv("https://pollofpolls.eu/get/polls/ES-parliament/format/csv")

knitr::opts_chunk$set(echo = FALSE)
```

```{r echo = FALSE, warning = FALSE}
# Creates a list of firms with data
good_firms <- spain_polling %>% 
  # Groups by firms
  
  group_by(firm) %>% 
  # Summarizing number of entries for each firm 
  
  summarize(number = n()) %>% 
  
  ungroup() %>% 
  # Selects for firms that have greater than 40 entries
  
  filter(number >= 40) %>% 
  pull(firm)
  
# Plots party percentage support with data taken from good firms
spain_polling %>% 
  filter(firm %in% good_firms) %>% 
  # Looks at data  from the past year
  
  filter(date > Sys.Date() - 365) %>%
  # Removing the columns we don't need
  
  select(-c(source, sd)) %>%
  gather(key = party, value = value, PP, PSOE, Cs, VOX, Podemos) %>%
  ggplot(aes(x = date, y = value, color = party)) +
  
  # Adds the data points to the graph
  
  geom_point() + 
  # Draws a line of best fit through the data
  
  geom_smooth(se = FALSE, method = "loess", na.rm = TRUE) +
  # Appropriate titls and labels
  
  labs(x = NULL, y = "Percentage Support", title = "Polling in Advance of Spanish Election on April 28",
       subtitle = "Popular support for VOX surges over last year", caption = "Data source: Poll of Polls")
```

